const products = [
  {
    _id: "1",
    name: "This is Name",
    image: "/images/airpods.jpg",
    description: "this is a description",
    brand: "Apple",
    category: "Samsung",
    price: "88.99",
    countInStock: 3,
    rating: 1.5,
    numReviews: 4,
  },
  {
    _id: "1",
    name: "This is Name",
    image: "/images/airpods.jpg",
    description: "this is a description",
    brand: "Apple",
    category: "Samsung",
    price: "88.99",
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: "1",
    name: "This is Name",
    image: "/images/airpods.jpg",
    description: "this is a description",
    brand: "Apple",
    category: "Samsung",
    price: "88.99",
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: "1",
    name: "This is Name",
    image: "/images/airpods.jpg",
    description: "this is a description",
    brand: "Apple",
    category: "Samsung",
    price: "88.99",
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: "1",
    name: "This is Name",
    image: "/images/airpods.jpg",
    description: "this is a description",
    brand: "Apple",
    category: "Samsung",
    price: "88.99",
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: "1",
    name: "This is Name",
    image: "/images/airpods.jpg",
    description: "this is a description",
    brand: "Apple",
    category: "Samsung",
    price: "88.99",
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
];

export default products;
